### ISSUE TITLE
Answers!

### ISSUE THREAD

**Issue by mattmassicotte** [OliveTreeBible/MXSymbolicate#1]
Hello! Thanks for creating this, and for letting me know (via [Meter](https://github.com/ChimeHQ/Meter/issues/3)).

I was browsing, and discovered your questions. So I thought I'd take a stab an answering them!

> In a crash diagnostic, how do I know which thread actually crashed?

Look for the `threadAttributed: true` property in the call stacks.

> What does the callStackPerThread property in the call stack mean?

The call stack structures aren't necessarily representative of a single thread. Apple uses, for better or worse, the same structure to represent sampling data, where you could have multiple root stacks for a single thread. I *think* this is what that property is trying to indicate.

> What's the purpose of the address field in the call stack frame objects?

I'm surprised to see this question, as the value is needed for symbolization. Did you end up figuring this out?

You need two values to symbolicate a stack frame. The actual runtime frame address as well as the load address of the binary it is from. Bizarrely, for *some* types of reports `offsetIntoBinaryTextSegment` is an actual an offset, and sometimes it is the load address. I had to jump though hoops to figure this out so that I could get symbolization working correctly. And its just incredibly confusing.

> What situations trigger disk write exceptions and CPU exceptions?

The OS triggers these when it decides that the process has exceeded a usage threshold. How those thresholds are determined I do not know, but they often say things like "exceeded 10 seconds of use" or something like that.

> What are the complete rules about where to find dSYM files for system frameworks?

You'll never find dSYMs for system frameworks, as Apple does not publish them. However, you can also symbolicate against the actual binaries themselves, which it seem like what your script is doing. This is also how Meter does on-device symbolication.

As far as I know, there are no rules. Normally, you will want to include in the report the full path to the loaded binary, but MetricKit only includes the binary name and it is honestly a huge pain. Spotlight indexes dSYMs by UUID, but it does not do the same thing for plain binaries unfortunately.

> Call stacks are formatted as recursive objects, with each frame having a subFrames object. Usually these contain only one object, but sometimes there's more. Why?
> Sometimes the callStackRootFrames array has more than one object in it. Why?

The answer to this question is the same as the `callStackPerThread` thing. Apple is using the same structure to represent both one-stack-per-thread data (like a crash) and a hierarchy of stacks (for a flame-graph style sample) you'd get from sampling a process.

You didn't ask this question, but I also wanted to point you at a wrapper I made for CoreSymbolication: https://github.com/ChimeHQ/CoreSymbolication. That's the library that atos uses internally, and is very powerful. Just in case you are interested in doing this work from Swift. I haven't looked at this recently, but if you are inspired, I'd love to pick it back up. And it'd be cool to work together!

**Comment by tomhamming** [comment]
I'm going to try to get a lab about this at WWDC 2024 and ask an engineer some of these questions. And also ask them _how they expect third-party developers to know the answers_. I don't understand how anyone can think the documentation on this is adequate.

**Comment by mattmassicotte** [comment]
Heh, that's actually quite funny! That `atos` invocation is basically saying "my binary was loaded at address 0x1. Which is definitely was not. But! It still works (most of the time, but not always!) because MetricKit returns a relative address (an offset), instead of an absolute address.

(also tiny note: you always want to run `atos` with the `-i` flag to resolve inlined functions)

Why 0x1 and not 0x0 you ask? Because stack addresses always contain a functions return address, which is 1 instruction past where they were invoked. But, you don't want the return location, you want the calling location. So if the machine's instruction width is 1 pointer in size, this works! 

Meter, the library you originally commented on, can symbolicate on-device. But its cannot do an excellent job for a number of reasons. You can get by for small volumes, but eventually it just becomes completely impractical to have all the OS libraries you need locally. On-device symbolication really shines here because the device always have the libraries that were in use (unless there was an OS upgrade in-between).

CoreSymbolication is a private framework, and while it is present on iOS devices, I'm not sure what it would get you to do use it. It is a way to do symbolication off of the device. So you could use CoreSymbolication to reimplement your python script in Swift. It would be more complex, but would run faster.
